### ISSUE TITLE
Build fails on Logger interface

### ISSUE THREAD

**Issue by martenlindblad** [trivago/nomad-pot-driver#22]
I am trying to building the driver on MacOS with GOOS=freebsd.
Command: `go build .`
Output:
```
./main.go:13:15: cannot use factory (type func("github.com/hashicorp/go-hclog".Logger) interface {}) as type plugins.PluginFactory in argument to plugins.Serve
./main.go:18:25: cannot use log (type "github.com/hashicorp/go-hclog".Logger) as type "github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-hclog".Logger in argument to pot.NewPotDriver:
	"github.com/hashicorp/go-hclog".Logger does not implement "github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-hclog".Logger (wrong type for Named method)
		have Named(string) "github.com/hashicorp/go-hclog".Logger
		want Named(string) "github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-hclog".Logger
```

**Comment by ebarriosjr** [comment]
Hi, which go version are you running?

**Comment by martenlindblad** [comment]
go version go1.13.5 darwin/amd64

**Comment by ebarriosjr** [comment]
I just did a clean build on an Mac with MacOS Mojave 10.14.6 with go1.14 and can not reproduce this. Will try to downgrade to go 1.13 and try.

**Comment by ebarriosjr** [comment]
Can't reproduce.
`$go version
go version go1.13.5 darwin/amd64
$ GOOS=freebsd go build -v .
internal/race
runtime/internal/sys
internal/cpu
runtime/internal/atomic
runtime/internal/math
sync/atomic
unicode
unicode/utf8
internal/bytealg
encoding
math/bits
internal/testlog
unicode/utf16
math
crypto/internal/subtle
crypto/subtle
container/list
vendor/golang.org/x/crypto/cryptobyte/asn1
runtime
internal/nettrace
vendor/golang.org/x/crypto/internal/subtle
vendor/golang.org/x/crypto/curve25519
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/resolver
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/internal
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/naming
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/resolver/passthrough
github.com/trivago/nomad-pot-driver/vendor/github.com/oklog/run
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/sys/cpu
github.com/trivago/nomad-pot-driver/vendor/github.com/vmihailenco/msgpack/codes
github.com/trivago/nomad-pot-driver/vendor/github.com/agext/levenshtein
internal/reflectlite
sync
internal/singleflight
math/rand
errors
sort
internal/oserror
io
strconv
vendor/golang.org/x/net/dns/dnsmessage
syscall
bytes
strings
reflect
bufio
hash
crypto
crypto/internal/randutil
crypto/hmac
crypto/rc4
vendor/golang.org/x/crypto/hkdf
hash/crc32
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/text/transform
internal/syscall/unix
time
vendor/golang.org/x/text/transform
path
html
text/tabwriter
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/encoding
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins/base/structs
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl/hcl/strconv
regexp/syntax
container/heap
encoding/base32
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/golang-lru/simplelru
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-immutable-radix
github.com/trivago/nomad-pot-driver/vendor/github.com/ryanuber/go-glob
context
internal/poll
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/net/context
github.com/trivago/nomad-pot-driver/vendor/github.com/LK4D4/joincontext
encoding/binary
os
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/errwrap
internal/fmtsort
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/internal/grpcrand
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/keepalive
encoding/base64
crypto/cipher
crypto/sha512
fmt
path/filepath
io/ioutil
crypto/aes
crypto/des
crypto/ed25519/internal/edwards25519
crypto/md5
crypto/sha1
crypto/sha256
encoding/pem
encoding/json
log
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-multierror
math/big
encoding/hex
vendor/golang.org/x/net/route
net/url
vendor/golang.org/x/crypto/internal/chacha20
net
vendor/golang.org/x/crypto/poly1305
vendor/golang.org/x/sys/cpu
vendor/golang.org/x/crypto/chacha20poly1305
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-hclog
github.com/trivago/nomad-pot-driver/vendor/github.com/golang/protobuf/proto
compress/flate
crypto/elliptic
encoding/asn1
crypto/rand
crypto/ed25519
crypto/ecdsa
crypto/rsa
crypto/dsa
crypto/x509/pkix
vendor/golang.org/x/crypto/cryptobyte
compress/gzip
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/net/http2/hpack
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/text/unicode/bidi
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/text/unicode/norm
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/text/secure/bidirule
vendor/golang.org/x/text/unicode/bidi
vendor/golang.org/x/text/secure/bidirule
vendor/golang.org/x/text/unicode/norm
crypto/x509
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/net/idna
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/net/lex/httplex
net/textproto
vendor/golang.org/x/net/http2/hpack
vendor/golang.org/x/net/idna
github.com/trivago/nomad-pot-driver/vendor/github.com/golang/protobuf/ptypes/any
github.com/trivago/nomad-pot-driver/vendor/github.com/golang/protobuf/ptypes/duration
github.com/trivago/nomad-pot-driver/vendor/github.com/golang/protobuf/ptypes/timestamp
mime
crypto/tls
github.com/trivago/nomad-pot-driver/vendor/github.com/golang/protobuf/ptypes
mime/quotedprintable
vendor/golang.org/x/net/http/httpguts
vendor/golang.org/x/net/http/httpproxy
mime/multipart
net/http/internal
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/net/internal/timeseries
text/template/parse
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/grpclog
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/codes
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/encoding/proto
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/connectivity
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/internal/backoff
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/internal/envconfig
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/genproto/googleapis/rpc/status
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/metadata
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/stats
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/status
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/tap
text/template
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/resolver/dns
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/yamux
github.com/trivago/nomad-pot-driver/vendor/github.com/mitchellh/go-testing-interface
encoding/gob
go/token
os/exec
os/signal
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/helper/pluginutils/grpcutils
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins/shared/hclspec
html/template
github.com/trivago/nomad-pot-driver/vendor/github.com/golang/protobuf/ptypes/wrappers
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins/shared/structs/proto
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl/hcl/token
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl/hcl/ast
regexp
os/user
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/sys/unix
archive/tar
net/http/httptrace
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/credentials
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/balancer
net/http
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/balancer/base
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/balancer/roundrobin
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/internal/channelz
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/peer
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/helper
github.com/trivago/nomad-pot-driver/vendor/github.com/gorhill/cronexpr
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-rootcerts
github.com/trivago/nomad-pot-driver/vendor/github.com/shirou/gopsutil/internal/common
github.com/trivago/nomad-pot-driver/vendor/github.com/mitchellh/mapstructure
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-version
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/golang-lru
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl/hcl/scanner
github.com/trivago/nomad-pot-driver/vendor/github.com/shirou/gopsutil/cpu
github.com/trivago/nomad-pot-driver/vendor/github.com/shirou/gopsutil/disk
github.com/trivago/nomad-pot-driver/vendor/github.com/shirou/gopsutil/mem
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/helper/stats
github.com/trivago/nomad-pot-driver/vendor/github.com/shirou/gopsutil/net
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl/hcl/parser
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl/json/token
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl/json/scanner
github.com/trivago/nomad-pot-driver/vendor/github.com/shirou/gopsutil/process
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/helper/args
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl/json/parser
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/helper/flatmap
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl
github.com/trivago/nomad-pot-driver/vendor/github.com/shirou/gopsutil/host
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/helper/uuid
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/lib/kheap
hash/crc64
github.com/trivago/nomad-pot-driver/vendor/github.com/mitchellh/reflectwalk
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/acl
hash/fnv
github.com/trivago/nomad-pot-driver/vendor/github.com/mitchellh/copystructure
github.com/trivago/nomad-pot-driver/vendor/github.com/mitchellh/hashstructure
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/crypto/blake2b
runtime/debug
github.com/trivago/nomad-pot-driver/vendor/gopkg.in/fsnotify.v1
github.com/trivago/nomad-pot-driver/vendor/gopkg.in/tomb.v1
github.com/trivago/nomad-pot-driver/vendor/github.com/hpcloud/tail/util
github.com/trivago/nomad-pot-driver/vendor/github.com/zclconf/go-cty/cty/set
github.com/trivago/nomad-pot-driver/vendor/github.com/vmihailenco/msgpack
github.com/trivago/nomad-pot-driver/vendor/github.com/hpcloud/tail/watch
github.com/trivago/nomad-pot-driver/vendor/github.com/zclconf/go-cty/cty
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/client/lib/fifo
github.com/trivago/nomad-pot-driver/vendor/github.com/apparentlymart/go-textseg/textseg
github.com/trivago/nomad-pot-driver/vendor/github.com/mitchellh/go-wordwrap
encoding/csv
github.com/trivago/nomad-pot-driver/vendor/github.com/davecgh/go-spew/spew
github.com/trivago/nomad-pot-driver/vendor/github.com/pmezard/go-difflib/difflib
github.com/trivago/nomad-pot-driver/vendor/gopkg.in/yaml.v2
flag
runtime/trace
github.com/trivago/nomad-pot-driver/vendor/github.com/zclconf/go-cty/cty/convert
github.com/trivago/nomad-pot-driver/vendor/github.com/zclconf/go-cty/cty/function
github.com/trivago/nomad-pot-driver/vendor/github.com/zclconf/go-cty/cty/msgpack
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl2/hcl
github.com/trivago/nomad-pot-driver/vendor/github.com/zclconf/go-cty/cty/gocty
github.com/trivago/nomad-pot-driver/vendor/github.com/zclconf/go-cty/cty/json
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl2/hcldec
github.com/trivago/nomad-pot-driver/vendor/github.com/zclconf/go-cty/cty/function/stdlib
testing
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl2/hcl/hclsyntax
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/net/trace
github.com/trivago/nomad-pot-driver/vendor/golang.org/x/net/http2
net/http/httputil
net/rpc
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-cleanhttp
github.com/trivago/nomad-pot-driver/vendor/github.com/armon/go-metrics
github.com/trivago/nomad-pot-driver/vendor/github.com/ugorji/go/codec
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/serf/coordinate
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/consul/api
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/hcl2/hcl/json
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/helper/pluginutils/hclspecutils
net/http/httptest
github.com/trivago/nomad-pot-driver/vendor/github.com/stretchr/testify/assert
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/internal/transport
github.com/trivago/nomad-pot-driver/vendor/github.com/stretchr/testify/require
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/health/grpc_health_v1
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins/base/proto
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-plugin/internal/proto
github.com/trivago/nomad-pot-driver/vendor/google.golang.org/grpc/health
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins/device/proto
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins/drivers/proto
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-plugin
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins/shared/structs
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins/base
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/raft
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins/device
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/client/stats
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/nomad/structs
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/client/structs
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/client/allocdir
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins/drivers
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/plugins
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/drivers/shared/eventer
github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/nomad/helper/pluginutils/hclutils
github.com/trivago/nomad-pot-driver/driver
github.com/trivago/nomad-pot-driver`

**Comment by martenlindblad** [comment]
That is odd. I will try on another computer tonight.
I just tried this in a completely clean GOPATH using version `go version go1.14 darwin/amd64`:
```
go get ./...                                                                                                                                                                   [±master ●]
# nomad-pot-driver/driver
driver/driver.go:153:37: cannot use logger (type "github.com/hashicorp/go-hclog".Logger) as type "github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-hclog".Logger in argument to eventer.NewEventer:
        "github.com/hashicorp/go-hclog".Logger does not implement "github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-hclog".Logger (wrong type for Named method)
                have Named(string) "github.com/hashicorp/go-hclog".Logger
                want Named(string) "github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-hclog".Logger
# nomad-pot-driver
./main.go:13:15: cannot use factory (type func("github.com/hashicorp/go-hclog".Logger) interface {}) as type plugins.PluginFactory in argument to plugins.Serve
./main.go:18:25: cannot use log (type "github.com/hashicorp/go-hclog".Logger) as type "github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-hclog".Logger in argument to pot.NewPotDriver:
        "github.com/hashicorp/go-hclog".Logger does not implement "github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-hclog".Logger (wrong type for Named method)
                have Named(string) "github.com/hashicorp/go-hclog".Logger
                want Named(string) "github.com/trivago/nomad-pot-driver/vendor/github.com/hashicorp/go-hclog".Logger
```
